<a href="https://colab.research.google.com/github/RyanKhurana9/Pytorch/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(torch.cuda.get_device_name(0))

else:
  print("No GPU available.Working on CPU")



No GPU available.Working on CPU


# Creating Tensor


In [ ]:
a=torch.empty(2,3)# basically allocates space and Returns a tensor containing whatever data was already present in that memory location

In [ ]:
a

tensor([[ 4.1881e-11,  1.6996e-04,  2.9571e-18],
        [ 4.4299e-41,  2.7951e-08, -1.5947e+14]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)# random values btw 0 and 1

tensor([[0.0160, 0.5363, 0.5058],
        [0.0315, 0.6155, 0.0425]])

In [ ]:
# to bring reproducibility in rand (seed)
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#build custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#arange
print("using arange",torch.arange(0,10,1))#start to end-1 and jump

using arange tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
#using linspace(linearly space)
print("using linspace",torch.linspace(0,10,10))#range 0 to 10 and get 10 evenly spaced values


using linspace tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
#eye for Identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
#using full specify dimension and the value which needs to be filled
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor shape


In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape


torch.Size([2, 3])

In [ ]:
# if we want to build a tensor exactly same shape(but the values will be different)
torch.empty_like(x)#same dimension as x but the values are different


tensor([[136110828109200,       431444496,       433262624],
        [      431443168,               0,       433261600]])

In [ ]:
torch.zeros_like(x)#build a tensor of same dimension as x but all the values will be 0

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
#torch.rand_like(x)# this will not work as our x contains integer values but rand generates float values btw 0 and 1

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Datatype


In [ ]:
x.dtype

torch.int64

In [ ]:
#assign datatype
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Mathematical Operation


In [ ]:
x=torch.rand(2,2)

In [ ]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


# Element wise operation

In [ ]:
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [ ]:
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [ ]:
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [ ]:
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [ ]:
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [ ]:
c=torch.tensor([1, -2, 3, -4])

In [ ]:
c

tensor([ 1, -2,  3, -4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.negative(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d,min=1,max=3)# brings the value in a tensor btw 1 and 3

tensor([1.9000, 2.3000, 3.0000, 3.0000])

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)# torch.randint() creates a tensor filled with random integers.

In [ ]:
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [ ]:
torch.sum(e)

tensor(24.)

In [ ]:
torch.sum(e,dim=1)# row wise addition

tensor([15.,  9.])

In [ ]:
torch.sum(e,dim=0)#column wise addition


tensor([ 8.,  0., 16.])

In [ ]:
torch.mean(e)

tensor(4.)

In [ ]:
torch.median(e)

tensor(0.)

In [ ]:
torch.max(e)

tensor(9.)

In [ ]:
torch.min(e)

tensor(0.)

In [ ]:
#product of all the elements
torch.prod(e)

tensor(0.)

In [ ]:
torch.std(e)

tensor(4.4272)

In [ ]:
torch.argmax(e)# return the index of the maximum element

tensor(5)

tensor([[5., 7., 3.],
        [9., 4., 0.]]).  but pytoch views it as[5., 7., 3., 9., 4., 0.]

In [ ]:
torch.argmin(e)#return the index of the minimum element

tensor(1)

# Matrix operation

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g =torch.randint(size=(3,2),low=0,high=10)
print(f)
print("*"*100)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
****************************************************************************************************
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [ ]:
# matrix multiplcation
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
f

tensor([[5, 7, 3],
        [9, 4, 0]])

In [ ]:
#swaps dimension 0 (rows) and dimension 1 (columns).
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [ ]:
#deteminant
t=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
t

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [ ]:
torch.det(t)

tensor(-110.)

In [ ]:
torch.inverse(t)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [ ]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
i>j

tensor([[ True,  True, False],
        [ True, False, False]])

In [ ]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
i>=j

tensor([[ True,  True, False],
        [ True, False, False]])

In [ ]:
i<=j

tensor([[False, False,  True],
        [False,  True,  True]])

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [ ]:
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [ ]:
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [ ]:
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [ ]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [ ]:
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [ ]:
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [ ]:
torch.softmax(k,dim=0)# dim=0, softmax is applied column-wise.

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

# Inplace operation


In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [ ]:
m+n# it create a completely new tensor in the data (this is not desireable )=>unnecessary occupation of space


tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [ ]:
m.add_(n)# does not create a new tensor just the values in side m are changed

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [ ]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [ ]:
torch.relu(m)# this also creates a new tensor and allocates memory
# to preveny that
m.relu()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

# Copying a tensor


In [ ]:
a=torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
b=a# it does not create a new memory but creates a reference pointer to that value

In [ ]:
a[0][0]=0

In [ ]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
b# if a changes b also changes

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
id(a)

136109759903968

In [ ]:
id(b)

136109759903968

In [ ]:
#instead of a=b we done
b=a.clone()

In [ ]:
a[0][0]=67

In [ ]:
a

tensor([[67.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [ ]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

# Tensor operation on GPU


In [ ]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

# Reshaping Tensor


In [ ]:
a=torch.ones(4,4)

In [ ]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)#(2 blocks,
 #2 groups per block,
 #2 rows per group,
 #2 columns per row)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])