<a href="https://colab.research.google.com/github/RyanKhurana9/Pytorch/blob/main/pytorch_nn_module_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out

In [ ]:
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.6202],
        [0.6471],
        [0.6523],
        [0.6556],
        [0.6553],
        [0.6199],
        [0.6599],
        [0.6277],
        [0.6445],
        [0.6286]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.0365,  0.3592, -0.2501,  0.0630,  0.1509],
        [ 0.0391,  0.0183,  0.3234, -0.0969,  0.3269],
        [-0.2058, -0.3972, -0.1659,  0.0181,  0.2115]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[-0.1213,  0.5003, -0.1791]], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

In [ ]:
summary(model,input_size=(features.shape))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00