<a href="https://colab.research.google.com/github/RyanKhurana9/Pytorch/blob/main/pytorch_nn_module_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

#in order to access the offerings given by the nn module the module class has to inherit it
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()# super().__init__() is used to call the constructor (__init__) of the parent class from a child class.
    self.linear=nn.Linear(num_features,1)#(number of input features,no of output features)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear(features)#z=wx+b
    out=self.sigmoid(out)#sigmoid(z)

    #internally __call__(magic function) is over written in nn.module class=>if class Model is called=>automaticallty forward class is triggered

    return out


Model gets the functionalities of nn.Module because it inherits from nn.Module.
super().__init__() initializes those functionalities so they work properly.

In [ ]:
features=torch.rand(10,5)#no of features=5 (columns) 10 rows
model=Model(features.shape[1])
#model.forward(features) ->this works but not recommended by pytorch

model(features)


tensor([[0.6442],
        [0.5282],
        [0.5601],
        [0.5948],
        [0.5892],
        [0.5979],
        [0.5976],
        [0.5331],
        [0.5685],
        [0.5249]], grad_fn=<SigmoidBackward0>)

In [ ]:
#to access weights=>model.linear.weights
model.linear.weight

Parameter containing:
tensor([[-0.3660,  0.2809,  0.2258,  0.1412,  0.3142]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.1097], requires_grad=True)

In [ ]:
!pip install torchinfo
##help to visualize the workflow

In [ ]:
from torchinfo import summary
summary(model,input_size=(features.shape))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00